name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci
      
      - name: Run npm run build
        run: npm run build
        
      - name: Run tests
        run: npm run test
        
      - name: Run e2e tests
        run: npm run test:e2e
